apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ocr-service
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - image:
        repoURL: asia-south1-docker.pkg.dev/tesseracthub-480811/ghcr-remote/tesserix/document-intelligence/ocr-service
        imageSelectionStrategy: NewestBuild
        allowTagsRegexes:
          - '^[a-f0-9]{40}$'
        strictSemvers: false
        discoveryLimit: 5
